name: Reusable Depoly
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        type: string
        required: false
        default: dist
    secrets:
      some-secret:
        required: false
    outputs:
      result:
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
      status:
        description: The status of the deployment operation
        value: '200'
jobs:
  deploy:
    outputs:
      # outcome: ${{ steps.set-result.outputs.my-result }}
      outcome: ${{ toJSON(steps.set-result.outputs) }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List file
        run: ls -al
      - name: Print secret text
        run: echo "some-secret=${{ secrets.some-secret }}"
      - name: Output information
        run: echo "Deploying & uploading..."
      - name: Set result output
        id: set-result
        run: |
          echo "my-result=success" >> $GITHUB_OUTPUT
          echo "my-status='200'" >> $GITHUB_OUTPUT
